### ISSUE TITLE
Improve esthetics

### ISSUE THREAD

**Issue by nt1m** [captainbrosset/domprofiler#6]
I should be able to submit a pull request by this weekend.

**Comment by captainbrosset** [comment]
Awesome!
I'm wondering if the whole thing shouldn't be rotated 90deg and be shown horizontally instead, as a timeline.
All records have associated timestamps (from `performance.now()`) so that's feasible.
Also a quick way to scroll through records while looking at the screenshots would help find the right spot (like the canvasdebugger in fact).

**Comment by nt1m** [comment]
@captainbrosset I guess the timeline idea would take too much space. It could be nice to add timestamps though. 

Anyways, did some styling improvements in Pull request #11

**Comment by captainbrosset** [comment]
Closing this issue now that your PR was merged.
Let's file new issues later when as we have more styling improvement ideas.
